# environments.yml
name: simuladordash
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.12
  - python-dateutil==2.8.2
  - pyjanitor==0.23.1
  - matplotlib==3.5.2
  - scipy==1.7.1
  - seaborn==0.11.2
  - scikit-learn==1.0.2
  - statsmodels==0.12.2
  - openpyxl
  - ipykernel==6.15.0
  - numpy==1.21.6
  - pandas==1.5.2
  - regex
  - dash==2.14.2
  - dash-daq==0.5.0
  - pip
  - pip:
    - dash_bootstrap_components==1.5.0
    - dash_html_components==2.0.15
    - dash_core_components==2.12.1
